-- 0051_seo_faq_buying.sql
-- SEO expansion: per-page FAQ (schema.org FAQPage source) and a
-- "buying pre-construction here" educational block, plus the page's
-- updated_at exposed publicly so sitemaps/UI can carry a real lastmod.
-- New view columns are APPENDED (CREATE OR REPLACE requirement).

alter table public.public_project_pages
  add column if not exists section_faq jsonb,
  add column if not exists section_buying text;

create or replace view public.public_projects_view as
 SELECT p.id AS project_id,
    pp.id AS public_page_id,
    pp.slug,
    pp.indexable,
    COALESCE(pp.seo_title, pp.page_title, p.project_name) AS seo_title,
    pp.seo_meta_description,
    pp.page_title,
    pp.page_summary,
    COALESCE(pp.page_description, p.description_long, p.description_short) AS page_description,
    pp.canonical_url,
    pp.custom_cta_text,
    pp.assigned_realtor_profile_id,
    pp.published_at,
    p.project_name,
    p.project_name_alt,
    p.headline,
    p.description_short,
    p.description_long,
    p.project_type,
    p.construction_status,
    p.sales_status,
    p.ownership_type,
    p.builder_name,
    p.architect_name,
    p.interior_designer_name,
    p.address_full,
    p.city,
    p.municipality,
    p.province,
    p.postal_code,
    p.neighbourhood,
    p.intersection_primary,
    p.intersection_secondary,
    p.latitude,
    p.longitude,
    p.occupancy_estimate_text,
    p.occupancy_start_date,
    p.occupancy_end_date,
    p.storeys,
    p.total_units,
    p.bedrooms_summary,
    p.bathrooms_summary,
    p.size_range_sqft_min,
    p.size_range_sqft_max,
    p.price_from_public,
    p.price_to_public,
    p.price_currency,
    COALESCE(pp.hero_image_url_override, p.hero_image_url) AS hero_image_url,
    p.hero_image_alt,
    p.cover_image_url,
    p.sales_centre_name,
    p.sales_centre_address,
    p.sales_centre_phone,
    p.sales_centre_email,
    p.sales_centre_hours,
    p.website_url,
    p.is_featured,
    p.is_advertiser,
    COALESCE(p.show_similar_override, NOT p.is_advertiser) AS show_similar_block,
    pp.section_intro,
    pp.section_amenities,
    pp.section_getting_around,
    pp.section_developer,
    pp.neighbourhood_features,
    pp.neighbourhood_home_stats,
    p.featured_rank,
    pp.section_faq,
    pp.section_buying,
    pp.updated_at AS page_updated_at
   FROM public_project_pages pp
     JOIN projects p ON p.id = pp.project_id
  WHERE pp.is_active = true AND p.public_page_enabled = true AND p.record_status = 'published'::text;
