-- =============================================================================
-- LIQWD — Migration 0081: brokerage article types (deep dives + head-to-heads)
-- -----------------------------------------------------------------------------
-- WHAT THIS DOES
--   Adds 'brokerage_profile' and 'brokerage_comparison' to the articles type
--   constraint. These are web-search-grounded pieces about named Ontario
--   brokerage brands, generated by src/lib/brokerage-content.ts under hard
--   rules: only publicly published terms (cited), "not published — negotiated
--   per office" stated explicitly where true, no rankings or winners, a
--   server-appended verification disclaimer, and the same mandatory human
--   review gate as all articles.
--
-- EXECUTION ORDER
--   Run after 0080_agent_guide_articles.sql.
-- =============================================================================

alter table public.articles drop constraint if exists articles_type_chk;
alter table public.articles add constraint articles_type_chk
  check (article_type in (
    'project_spotlight',
    'neighbourhood_guide',
    'comparison',
    'market_update',
    'agent_guide',
    'brokerage_profile',
    'brokerage_comparison'
  ));
