-- =============================================================================
-- LIQWD — Migration 0086: consumer_guide article type
-- -----------------------------------------------------------------------------
-- WHAT THIS DOES
--   Adds 'consumer_guide' to the articles type constraint: evergreen
--   consumer-facing explainers (first wave: assignment-seller content that
--   feeds /assignment-value — "can I sell my pre-construction condo before
--   closing", assignment costs & HST, interim occupancy). Generated by the
--   briefed-piece engine (src/lib/brokerage-content.ts) under a
--   plain-language, not-advice ruleset; same editor gate as everything else.
--
-- EXECUTION ORDER
--   Run after 0085_assignment_valuation_requests.sql.
-- =============================================================================

alter table public.articles drop constraint if exists articles_type_chk;
alter table public.articles add constraint articles_type_chk
  check (article_type in (
    'project_spotlight',
    'neighbourhood_guide',
    'comparison',
    'market_update',
    'agent_guide',
    'brokerage_profile',
    'brokerage_comparison',
    'consumer_guide'
  ));
